apiVersion: v1
entries:
  istio-all:
  - annotations:
      artifacthub.io/category: networking
      artifacthub.io/containsSecurityUpdates: "false"
      artifacthub.io/license: Apache-2.0
    apiVersion: v2
    appVersion: 1.24.2
    created: "2025-01-01T18:43:27.214068-05:00"
    dependencies:
    - name: ambient
      repository: https://istio-release.storage.googleapis.com/charts
      version: 1.24.2
    - alias: kiali
      condition: kiali.enabled
      name: kiali-server
      repository: https://kiali.org/helm-charts
      version: 1.89.3
    - condition: prometheus.enabled
      name: prometheus
      repository: https://prometheus-community.github.io/helm-charts
      version: 25.27.0
    description: A Helm chart to insall all Istio Components, along with minimal kiali
      and prometheus in Kubernetes Cluster
    digest: ba9a8b69b71ffda6a8c48fba036f241dc6f1af76cccbc700b70151b460446648
    icon: https://code4devs.github.io/logo.png
    keywords:
    - istio
    - ambient
    - istio-cni
    - ztunnel
    - kiali-server
    - prometheus
    - Observability
    - Monitoring
    - service-mesh
    kubeVersion: '>=1.27.0'
    name: istio-all
    type: application
    urls:
    - istio-all/istio-all-1.2.0.tgz
    version: 1.2.0
  - annotations:
      artifacthub.io/category: networking
      artifacthub.io/containsSecurityUpdates: "false"
      artifacthub.io/license: Apache-2.0
    apiVersion: v2
    appVersion: 1.23.2
    created: "2025-01-01T18:43:27.189047-05:00"
    dependencies:
    - name: base
      repository: https://istio-release.storage.googleapis.com/charts
      version: 1.23.2
    - name: istiod
      repository: https://istio-release.storage.googleapis.com/charts
      version: 1.23.2
    - condition: ztunnel.enabled
      name: ztunnel
      repository: https://istio-release.storage.googleapis.com/charts
      version: 1.23.2
    - condition: cni.enabled
      name: cni
      repository: https://istio-release.storage.googleapis.com/charts
      version: 1.23.2
    - alias: ingressgateway
      condition: ingressgateway.enabled
      name: gateway
      repository: https://istio-release.storage.googleapis.com/charts
      version: 1.23.2
    - alias: egressgateway
      condition: egressgateway.enabled
      name: gateway
      repository: https://istio-release.storage.googleapis.com/charts
      version: 1.23.2
    - alias: kiali
      condition: kiali.enabled
      name: kiali-server
      repository: https://kiali.org/helm-charts
      version: 1.89.3
    - condition: prometheus.enabled
      name: prometheus
      repository: https://prometheus-community.github.io/helm-charts
      version: 25.27.0
    description: A Helm chart to insall all Istio Components, along with minimal kiali
      and prometheus in Kubernetes Cluster
    digest: 07bf6d25d121649a559d58dcba755195cfe1661b54778826bb96589d3c1e9f9d
    icon: https://code4devs.github.io/logo.png
    keywords:
    - istio
    - istio-gateway
    - istio-cni
    - ztunnel
    - kiali-server
    - prometheus
    - Observability
    - Monitoring
    - service-mesh
    kubeVersion: '>=1.27.0'
    name: istio-all
    type: application
    urls:
    - istio-all/istio-all-1.1.0.tgz
    version: 1.1.0
  - annotations:
      artifacthub.io/category: networking
      artifacthub.io/containsSecurityUpdates: "false"
      artifacthub.io/license: Apache-2.0
    apiVersion: v2
    appVersion: 1.23.2
    created: "2025-01-01T18:43:27.161415-05:00"
    dependencies:
    - name: base
      repository: https://istio-release.storage.googleapis.com/charts
      version: 1.23.2
    - name: istiod
      repository: https://istio-release.storage.googleapis.com/charts
      version: 1.23.2
    - condition: ztunnel.enabled
      name: ztunnel
      repository: https://istio-release.storage.googleapis.com/charts
      version: 1.23.2
    - condition: cni.enabled
      name: cni
      repository: https://istio-release.storage.googleapis.com/charts
      version: 1.23.2
    - alias: ingressgateway
      condition: ingressgateway.enabled
      name: gateway
      repository: https://istio-release.storage.googleapis.com/charts
      version: 1.23.2
    - alias: egressgateway
      condition: egressgateway.enabled
      name: gateway
      repository: https://istio-release.storage.googleapis.com/charts
      version: 1.23.2
    - alias: kiali
      condition: kiali.enabled
      name: kiali-server
      repository: https://kiali.org/helm-charts
      version: 1.89.3
    - condition: prometheus.enabled
      name: prometheus
      repository: https://prometheus-community.github.io/helm-charts
      version: 25.27.0
    description: A Helm chart to insall all Istio Components, along with minimal kiali
      and prometheus in Kubernetes Cluster
    digest: 3a87dc371b1cf604a78c577a44830a71a979c2267a820a9999a123eed1559144
    icon: https://code4devs.github.io/logo.png
    keywords:
    - istio
    - istio-gateway
    - istio-cni
    - kiali-server
    - prometheus
    - Observability
    - Monitoring
    - service-mesh
    kubeVersion: '>=1.27.0'
    name: istio-all
    type: application
    urls:
    - istio-all/istio-all-1.0.0.tgz
    version: 1.0.0
  istio-control-plane:
  - annotations:
      artifacthub.io/category: networking
      artifacthub.io/containsSecurityUpdates: "false"
      artifacthub.io/license: Apache-2.0
    apiVersion: v2
    appVersion: 1.24.2
    created: "2025-01-01T18:43:27.225182-05:00"
    dependencies:
    - name: ambient
      repository: https://istio-release.storage.googleapis.com/charts
      version: 1.24.2
    description: A Helm chart to insall all Istio Control Panel in Kubernetes Cluster
    digest: f99d86aa9af1a2f860ff3f4e9800fd2e196589682d05baf6b757dba8e7600356
    icon: https://code4devs.github.io/logo.png
    keywords:
    - istio
    - ambient
    - istio-cni
    - ztunnel
    - service-mesh
    kubeVersion: '>=1.28.0'
    name: istio-control-plane
    type: application
    urls:
    - istio-control-plane/istio-control-plane-1.0.0.tgz
    version: 1.0.0
  istio-data-plane:
  - annotations:
      artifacthub.io/category: networking
      artifacthub.io/containsSecurityUpdates: "false"
      artifacthub.io/license: Apache-2.0
    apiVersion: v2
    appVersion: 1.24.2
    created: "2025-01-01T18:43:27.245941-05:00"
    dependencies:
    - condition: ingressgateway.enabled
      name: ingressgateway
      repository: ""
      version: 1.2.0
    - alias: egressgateway
      condition: egressgateway.enabled
      name: egress-waypoint
      repository: ""
      version: 1.0.0
    - alias: kiali
      condition: global.monitoring.enabled
      name: kiali-server
      repository: https://kiali.org/helm-charts
      version: 2.3.0
    - condition: global.monitoring.enabled
      name: prometheus
      repository: https://prometheus-community.github.io/helm-charts
      version: 26.0.1
    description: A Helm chart to insall all Istio Components, along with minimal kiali
      and prometheus in Kubernetes Cluster
    digest: fe1314a225c0579dd8caa336bd9b0265bf477bb54b1d172d86e0a16d89432cf8
    icon: https://code4devs.github.io/logo.png
    keywords:
    - istio
    - ambient
    - istio-cni
    - ztunnel
    - kiali-server
    - prometheus
    - Observability
    - Monitoring
    - service-mesh
    kubeVersion: '>=1.28.0'
    name: istio-data-plane
    type: application
    urls:
    - istio-data-plane/istio-data-plane-1.0.0.tgz
    version: 1.0.0
generated: "2025-01-01T18:43:27.130633-05:00"
