apiVersion: v1
entries:
  istio-all:
  - apiVersion: v2
    appVersion: 1.23.1
    created: "2024-09-22T11:25:32.555072-04:00"
    dependencies:
    - name: base
      repository: '@istio'
      version: 1.23.1
    - name: istiod
      repository: '@istio'
      version: 1.23.1
    - condition: ztunnel.enabled
      name: ztunnel
      repository: '@istio'
      version: 1.23.1
    - condition: cni.enabled
      name: cni
      repository: '@istio'
      version: 1.23.1
    - alias: ingressgateway
      condition: ingressgateway.enabled
      name: gateway
      repository: '@istio'
      version: 1.23.1
    - alias: egressgateway
      condition: egressgateway.enabled
      name: gateway
      repository: '@istio'
      version: 1.23.1
    - alias: kiali
      condition: kiali.enabled
      name: kiali-server
      repository: '@kiali'
      version: 1.89.0
    - condition: prometheus.enabled
      name: prometheus
      repository: '@prometheus-community'
      version: 25.8.2
    description: A Helm chart to Istio all Components in Kubernetes Cluster
    digest: d295d5931808bc90b5429ad11c1be85dc1728fa1dd5cdfff83fa17a0ed9890b8
    kubeVersion: '>=1.30.0'
    name: istio-all
    type: application
    urls:
    - istio-all/istio-all-1.0.0.tgz
    version: 1.0.0
generated: "2024-09-22T11:25:32.528303-04:00"
